server.port=8086
spring.data.mongodb.database=offer_ride
spring.data.mongodb.uri=mongodb://localhost:27017/
server.error.include-message=always

# Must match Auth service secret exactly
jwt.secret=MyOptimumPoolSuperSecretKey2024XYZ

spring.main.allow-bean-definition-overriding=true

# Web configuration to expose the health endpoint
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/